In [1]:
import pandas as pd

df = pd.read_excel("string_matched.xlsx")

df.head()

Review  Liked  price  quality  \
0                           Wow... Loved this place.      1      0        0   
1                                 Crust is not good.      0      0        1   
2          Not tasty and the texture was just nasty.      0      0        1   
3  Stopped by during the late May bank holiday of...      1      0        0   
4  The selection on the menu was great and so wer...      1      1        1   

   quantity  location  
0         0         1  
1         0         0  
2         0         0  
3         0         0  
4         0         0

Keywords

In [2]:
df_script = pd.read_excel("for_script.xlsx")
df_script = df_script.fillna(0)

df_price = df_script[df_script["price"] == 1]
df_quality = df_script[df_script["quality"] == 1]
df_quantity = df_script[df_script["quantity"] == 1]
df_location = df_script[df_script["location"] == 1]

import numpy as np

arr_price = list(df_price["vocabulary"])
arr_quality = list(df_quality["vocabulary"])
arr_quantity = list(df_quantity["vocabulary"])
arr_location = list(df_location["vocabulary"])

print(arr_price)
print(arr_quality)
print(arr_quantity)
print(arr_location)

['afford', 'buck', 'cheap', 'cost', 'discount', 'expens', 'fare', 'free', 'gratuiti', 'inexpens', 'price', 'pricey', 'spend', 'worth']
['averag', 'bad', 'best', 'clean', 'creami', 'crispi', 'crumbi', 'crusti', 'disgrac', 'disgust', 'dri', 'driest', 'eew', 'fine', 'flavorless', 'good', 'great', 'greatest', 'horribl', 'nasti', 'nice', 'perfect', 'qualiti', 'sad', 'salti', 'satifi', 'satisfi', 'tasti', 'yucki', 'yummi']
['amount', 'ampl', 'enough', 'gener', 'larg', 'larger', 'portion', 'quantiti', 'small', 'smaller']
['airport', 'ambianc', 'ambienc', 'area', 'arriv', 'garden', 'joint', 'place', 'quaint']


In [3]:
arr_price = list(arr_price)
print(type(arr_price))

<class 'list'>


In [4]:
from empath import Empath

lexicon = Empath()

lexicon.create_category("food-price",arr_price)
lexicon.create_category("food-quality",arr_quality)
lexicon.create_category("food-quantity",arr_quantity)
lexicon.create_category("restaurant-location",arr_location)

["afford", "cost", "money", "price", "costs", "worth", "budget", "sell", "pay", "paycheck", "insurance", "buy", "pay", "good_money", "cost", "salary", "more_money", "fortune", "cheap", "profit", "rent", "worth", "costing", "expenses", "costed", "wages", "allowance", "enough_money", "earn", "invest", "savings", "little_money", "income", "college_fund", "as_much_money", "bills", "paychecks", "cheaper", "discount", "tax", "that_much_money", "taxes", "extra_money", "guaranteed", "donate", "provide", "thousands_of_dollars", "purchase", "luxuries", "funds", "paid", "millions_of_dollars", "luxury", "sold", "supply", "work", "tuition", "mortgage", "own_money", "charity", "bankrupt", "so_much_money", "minimum_wage", "bank_account", "job", "pocket_money", "waste", "stocks", "expensive", "much_money", "fee", "repairs", "wage", "fund", "saving", "big_money", "trade", "qualify", "deposit", "how_much_money", "cheapest", "debt", "monthly", "a_hundred_dollars", "offer", "buying", "gamble", "decent_amo

In [14]:
emp_price = []
emp_quality = []
emp_quantity = []
emp_location = []

cat = ["food-price","food-quality","food-quantity","restaurant-location"]

reviews = df["Review"]

for line in reviews:

    curr = lexicon.analyze(line,cat)

    emp_price.append(curr["food-price"])
    emp_quality.append(curr["food-quality"])
    emp_quantity.append(curr["food-quantity"])
    emp_location.append(curr["restaurant-location"])

print(len(reviews))
print(len(emp_price))
print(len(emp_quality))
print(len(emp_quantity))
print(len(emp_location))

997
997
997
997
997


In [22]:
#print(emp_price)
#print(emp_quality)
#print(emp_quantity)
#print(emp_location)

In [25]:
liked = df["Liked"]

from numpy import corrcoef

print(corrcoef(liked,emp_price))
print(corrcoef(liked,emp_quality))
print(corrcoef(liked,emp_quantity))
print(corrcoef(liked,emp_location))

[[ 1.         -0.04992298]
 [-0.04992298  1.        ]]
[[1.         0.13680166]
 [0.13680166 1.        ]]
[[ 1.         -0.03288482]
 [-0.03288482  1.        ]]
[[1.         0.02695927]
 [0.02695927 1.        ]]
